---
# The NFS storage plugin is always enabled since it doesn't require any
# additional package dependencies
- name: NFS storage plugin configuration
  include: nfs.yml
  when: not openshift.common.is_containerized | bool

- name: GlusterFS storage plugin configuration
  include: glusterfs.yml
  when: "'glusterfs' in openshift.node.storage_plugin_deps and not openshift.common.is_containerized | bool "

- name: Ceph storage plugin configuration
  include: ceph.yml
  when: "'ceph' in openshift.node.storage_plugin_deps and not openshift.common.is_containerized | bool"
